version: "3"
services:
  jupyter:
    image: jupyter/sparkmagic
    build:
      context: .
      dockerfile: Dockerfile.jupyter
      args:
        dev_mode: "true"
    ports:
      - "8888:8888"
    env_file:
      - ./spark.env
    volumes:
      - ${HOME}/Code/signifyd/jupyter_notebooks:/home/jovyan/work
