version: "3"
services:
  jupyter:
    image: jupyter/sparkmagic
    build:
      context: .
      dockerfile: Dockerfile.jupyter
      args:
        dev_mode: "false"
    ports:
      - "8888:8888"
    extra_hosts:
      - "spark:10.5.5.170"